### PR TITLE
"Develop foreach attraction page and slider."

### PR DESCRIPTION
**Pull request by Tankliu6**
Hi Chao-Wei Peng,

I am Yen-Cheng, below is the url of task.

[slider](http://13.114.58.241:3000/)

thank you

Liu

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Slider should extend to full width in mobile version.
2. Text color in home page should keep align with design even if we add link to them.

**Comment by Tankliu6** [comment]
Hi Chao-Wei Peng,

I am Yen-Cheng, below is the url for fixed webpage.

[slider](http://13.114.58.241:3000/)

thank you

Liu

**Review by cwpeng — APPROVED** [review]
OK. Done.

You can try to use Flask Blueprint to seperate API routes from app.py

**Comment by Tankliu6** [comment]
OK. I will try to use Flask Blueprint.

Best regard

Liu

**Pull request merged**
