### PR TITLE
Develop homepage categories-search

### PR DESCRIPTION
**Pull request by Tankliu6**
Hello Chao-Wei Peng,

I'm Yen_Cheng, please check the below develop project.

[develop homepage](http://13.114.58.241:3000/)

best regard

Liu

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Try to use position:absolute to float category block on top of content.
2. Hide category block after we click one of them.

**Comment by Tankliu6** [comment]
Hello Chao-Wei Peng,

I'm Yen_Cheng, I have fixed the problems below.

1. Try to use position:absolute to float category block on top of content.

2. Hide category block after we click one of them.


[develop homepage](http://13.114.58.241:3000/)

best regard

Liu

**Comment by cwpeng** [comment]
Re-request review from right side in this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
