### PR TITLE
Develop member login, logout,signout and JWT

### PR DESCRIPTION
**Pull request by Tankliu6**
Hi, Chao-Wei Peng
I am Yen-Cheng, below is the project url.

[JWT](http://13.114.58.241:3000/)

thanks

Liu

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. It makes no sense of your input rule for name.
2. Even if I try to follow your rule, I cannot sign up.
3. Password input should use input element with type password.

**Comment by Tankliu6** [comment]
Hi, Chao-Wei Peng
I am Yen-Cheng, below is the project url after fix.

[JWT](http://13.114.58.241:3000/)

thanks

Liu

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your rule for name makes no sense. It's name, something like 王小明, not account or username for signin validation.

**Comment by Tankliu6** [comment]
Hi, Chao-Wei Peng
I am Yen-Cheng, below is the project url after username regex fix.

[JWT](http://13.114.58.241:3000/)

thanks

Liu

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
